#!/bin/bash

# Authentication API Testing Guide
# Test the registration and login endpoints

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║        Authentication API Testing Guide                            ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Make sure the server is running: npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 1: User Registration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "curl -X POST http://localhost:5000/api/users/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\":\"John Doe\",\"email\":\"john@example.com\",\"password\":\"test123\",\"age\":25}'"
echo ""
echo "Expected Response:"
echo "{"
echo "  \"success\": true,"
echo "  \"token\": \"eyJhbGciOiJIUzI1NiIs...\","
echo "  \"data\": {"
echo "    \"id\": \"...\","
echo "    \"name\": \"John Doe\","
echo "    \"email\": \"john@example.com\","
echo "    \"age\": 25,"
echo "    \"role\": \"user\""
echo "  }"
echo "}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 2: User Login"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "curl -X POST http://localhost:5000/api/users/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"john@example.com\",\"password\":\"test123\"}'"
echo ""
echo "Expected Response:"
echo "{"
echo "  \"success\": true,"
echo "  \"token\": \"eyJhbGciOiJIUzI1NiIs...\","
echo "  \"data\": {"
echo "    \"id\": \"...\","
echo "    \"name\": \"John Doe\","
echo "    \"email\": \"john@example.com\","
echo "    \"age\": 25,"
echo "    \"role\": \"user\""
echo "  }"
echo "}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 3: Login with Invalid Password"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "curl -X POST http://localhost:5000/api/users/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"john@example.com\",\"password\":\"wrongpassword\"}'"
echo ""
echo "Expected Response (401):"
echo "{"
echo "  \"success\": false,"
echo "  \"message\": \"Invalid email or password\""
echo "}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 4: Get All Users with Token"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command (replace TOKEN with actual token from login):"
echo "curl http://localhost:5000/api/users \\"
echo "  -H 'Authorization: Bearer TOKEN'"
echo ""
echo "Expected Response (200):"
echo "{"
echo "  \"success\": true,"
echo "  \"data\": [...users...],"
echo "  \"pagination\": {...}"
echo "}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 5: Duplicate Email Registration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command (same email as TEST 1):"
echo "curl -X POST http://localhost:5000/api/users/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\":\"Another User\",\"email\":\"john@example.com\",\"password\":\"test123\"}'"
echo ""
echo "Expected Response (400):"
echo "{"
echo "  \"success\": false,"
echo "  \"message\": \"User with this email already exists\""
echo "}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "USING POSTMAN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Create new request"
echo "2. Set method to POST"
echo "3. Enter URL: http://localhost:5000/api/users/register"
echo "4. Go to Body tab, select raw, JSON"
echo "5. Paste:"
echo "{"
echo "  \"name\": \"John Doe\","
echo "  \"email\": \"john@example.com\","
echo "  \"password\": \"test123\","
echo "  \"age\": 25"
echo "}"
echo "6. Click Send"
echo ""
echo "For Login:"
echo "1. New request, POST"
echo "2. URL: http://localhost:5000/api/users/login"
echo "3. Body (raw JSON):"
echo "{"
echo "  \"email\": \"john@example.com\","
echo "  \"password\": \"test123\""
echo "}"
echo "4. Click Send, copy the token from response"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ENVIRONMENT SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Add to .env file:"
echo "JWT_SECRET=your-secret-key-change-in-production"
echo "JWT_EXPIRE=7d"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
