#!/bin/bash
# Quick Start Guide for Rate Limiter

echo "=== Rate Limiter Quick Start ==="
echo ""
echo "✅ Installation Status:"
npm list express-rate-limit 2>/dev/null | head -2
echo ""
echo "📁 Project Structure:"
echo "middleware/rateLimiter.js          - Main rate limiter config"
echo "middleware/rateLimiterExamples.js  - Advanced examples"
echo "middleware/RATE_LIMITER_TESTING.js - Testing guide"
echo "RATE_LIMITER_README.md             - Full documentation"
echo ""
echo "🚀 To Start the Server:"
echo "  npm run dev        # Development with nodemon"
echo "  npm start          # Production"
echo ""
echo "📊 Rate Limiter Configuration:"
echo "  Limit: 100 requests per IP"
echo "  Window: 15 minutes"
echo "  Status Code: 429 (Too Many Requests)"
echo ""
echo "🧪 To Test the Rate Limiter:"
echo "  1. Start the server: npm run dev"
echo "  2. In another terminal, run:"
echo "     for i in {1..105}; do curl http://localhost:5000/api/users; done"
echo "  3. Requests 1-100 will succeed (200 status)"
echo "  4. Requests 101+ will return 429 status"
echo ""
echo "📝 Key Files Modified:"
echo "  server.js          - Added rate limiter import and middleware"
echo "  package.json       - Added express-rate-limit dependency"
echo ""
echo "💡 Tips:"
echo "  - Rate limiter must be applied BEFORE routes"
echo "  - Check response headers for RateLimit-Remaining"
echo "  - Use different limiters for different endpoints"
echo "  - For Redis storage, see RATE_LIMITER_README.md"
echo ""
echo "📖 See RATE_LIMITER_README.md for full documentation"
